# Generated by Django 4.2.7 on 2023-11-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Leaderboard',
        ),
    ]
